### ISSUE TITLE
Question quantify probabilistic confidence

### ISSUE THREAD

**Issue by mimisikai** [dmcable/spacexr#115]
When running the "multi" model, I wonder if any numeric value can be used to quantify the results. That will give us the flexibility to show some subsets (most significant or confidence highest) if applying a cut-off threshold.  Thanks.

**Comment by dmcable** [comment]
It currently doesn't save the numeric scores, but the cutoffs can be changed with the following two parameters in `create.RCTD`:
@param CONFIDENCE_THRESHOLD (Default 10) the minimum change in likelihood (compared to other cell types) necessary to determine a cell type identity with confidence
@param DOUBLET_THRESHOLD (Default 25) the penalty weight of predicting a doublet instead of a singlet for a pixel

**Comment by mimisikai** [comment]
Thanks. I want to try single cell but see it has been deprecated?

**Comment by dmcable** [comment]
If you want to probabilistically assign a single cell type, then you are correct that multi mode (and other modes) will not save the single cell type scores. However, it is possible to obtain the scores using RCTD's internal function `get_singlet_score` (or modifying the RCTD code to save the scores). For the first option, please see in the code for the singlets in "Compute the log likelihood of each subtype according to RCTD" within: https://raw.githack.com/dmcable/spacexr/master/AnalysisPaper/MainFigures/figure5-all.html.
