### ISSUE TITLE
Question regarding deconvolution of multi-tissue data

### ISSUE THREAD

**Issue by Dillon214** [dmcable/spacexr#131]
Hello spacexr developers,

I found this tool was used by a variety of successful publications, and would like to use it to analyze my own spatial data. I have one question about teh proper approach, though. 

My visium samples can be broadly seperated by tissue, disease, and timepoint, and I was wondering whether it would be more appropriate to use one merged referece including cell types from both tissues, or instead split my samples by tissue and run them each with the appropriate referece dataset for its given tissue, then merge the data again after the fact. I'm not sure if it bears mentioning or not, but the two tissues I have definitely share certain cell types.

**Comment by dmcable** [comment]
Both solutions are reasonable, and it is an empirical question of which approach will work better, but you have to weight the tradeoffs between the two approaches. By splitting the references, you will have more noise in the reference due to a smaller sample size in computing cell type averages. In merging the references, you could miss slightly different cell type definitions across samples, although I would be surprised if this were a substantial effect. I would typically opt for the single merged-reference approach out of simplicity.

**Comment by Dillon214** [comment]
Hi dmcable,

Thanks for the advice. Yeah, I thought it would end up being fine processing either way, just wanted to check with the creators. I'll go with your suggestion.
