### ISSUE TITLE
Error in !myRCTD@internal_vars$cell_types_assigned: invalid argument type

### ISSUE THREAD

**Issue by AmoriLi** [dmcable/spacexr#52]
Hi,
when running 'myRCTD<-run.CSIDE.single(myRCTD,explanatory.variable,doublet_mode = F,cell_types = cell_types)', I got the error message.  

myRCTD is full-mode result. cell_types=rownames(myRCTD@internal_vars$class_df).

Here is the detail error information.

![image](https://user-images.githubusercontent.com/80192100/150775223-4939c3c0-b3f0-4d04-8def-870e551653a2.png)

**Comment by dmcable** [comment]
Hello Amori,

This is most likely due to the `@internal_vars$cell_types_assigned` variable being unassigned, which would be the case if the `RCTD` object was created with an old version.

If cell types have been assigned, then running the following line of code prior to running CSIDE should fix your issue:
`myRCTD <- set_cell_types_assigned(myRCTD)`

This issue has been fixed now in the code, so that the appropriate error message will output.

Best,
Dylan
