### ISSUE TITLE
returns error if the reference dataset is large

### ISSUE THREAD

**Issue by sinanugur** [dmcable/spacexr#77]
Hello. I got the following error when I am working on large datasets. It works fine if there are fewer dimensions. My version is spacexr_2.0.0

```
loaded spacexr and set parent environment
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
Calls: data.frame ... as.data.frame -> as.matrix -> as.matrix -> as -> asMethod
```

**Comment by dmcable** [comment]
Hello, can you please post more details about which function triggered this error, the size of the reference, and the memory of your session? Thank you.

**Comment by sinanugur** [comment]
Sure. I downloaded two public datasets: query is https://www.dropbox.com/sh/qmhdbqh56cp0t3n/AACYo857F9VM98XdWtih2Aeoa/Spatial/Spatial_A1_adult.RDS?dl=0

and the reference scRNA dataset is https://www.dropbox.com/sh/qmhdbqh56cp0t3n/AABcNmrz7Qvy5SxSbB5-0rbIa/Single%20Cell/all_compartments.RDS?dl=0

When running the RCTD commands like this,

```
myRCTD <- create.RCTD(puck,reference,max_cores = 10,UMI_min = 20)
myRCTD <- run.RCTD(myRCTD,doublet_mode = "full")
```

It crashes and returns the error above. If I use another smaller reference (e.g. https://www.dropbox.com/sh/qmhdbqh56cp0t3n/AABdUzwfH6rrktxN1yHqOl4qa/Single%20Cell/neural.RDS?dl=0), it runs without a problem.

I observed the same result on a Linux HPC machine and on an Apple Silicon M1 laptop with 64GB ram. I guess it is not a RAM issue. Linux server also has around 1TB of RAM. Cheers.

**Comment by dmcable** [comment]
Hi Sinan,

I ran your script, and I think changing the following line resolves the error:
`counts <- data.frame(scrna_data@assays$RNA@counts)` causes error
`counts <- (scrna_data@assays$RNA@counts)` better

Please note, according to the `Reference` documentation, the counts matrix should be a `matrix` or `dgCmatrix` object, rather than a data.frame. I believe that creating such a large dataframe was creating the issue, but can be avoided by keeping it as a matrix.

Best,
Dylan

**Comment by sinanugur** [comment]
Thanks for the tip. Now it works!

Cheers,
