### ISSUE TITLE
'counts does not contain integers' when construct a single cell object

### ISSUE THREAD

**Issue by xiaoxiaofuyou** [dmcable/spacexr#78]
Dear authors:
When i trying to construct a single cell object from a h5ad file, i got this error:

![image](https://user-images.githubusercontent.com/105490459/172389604-559a3b9f-e8f0-489b-ad42-9d6be51fb48d.png)

my count(i had set it as a matrix) looked like this:

![image](https://user-images.githubusercontent.com/105490459/172390240-802659e2-2a39-49b6-8abf-0959e067eb08.png)

Could please help me to solve this problem, appreciate it very much!

**Comment by xiaoxiaofuyou** [comment]
Oh, it works! Thanks for your useful solution.

**Comment by JZL** [comment]
Hi,

Huh, confusing error message I had to think about it (the reason you're getting that error is data.tables can have each column have a different variable type).

I think the problem is that your counts type is not a matrix (if you run `class(counts)` it's probably `data.table` or `tibble` not `matrix` or `Matrix`. Without knowing its type, it's hard to know the exact function to run but if it is a data.table, try
```
new_counts = as.matrix(old_mtx)
```
and see what happens. Also make sure that the `colnames` and `rownames` stay the same before and after

**Comment by JZL** [comment]
Oh! I just saw the part where you said your counts was a matrix. Huh, huh!

But still check `class(counts)` because if it is a matrix it should return one of the types I put above, and there should only be one type/class for the whole variable, not a list (which is what I think the error is saying is happening)
